# Generated by Django 4.1.2 on 2022-10-30 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='reading',
            name='tenant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reading.tenant'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='house_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reading.house'),
        ),
    ]
