# Generated by Django 4.1.2 on 2022-10-30 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0004_house_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlyBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.CharField(max_length=255)),
                ('bill_type', models.CharField(max_length=255)),
                ('bill', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='tenant',
            name='house_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='reading.house'),
            preserve_default=False,
        ),
    ]
