# Generated by Django 4.1.2 on 2022-10-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0006_remove_house_status_house_color_house_is_occupied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearlybill',
            name='bill',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
