# Generated by Django 4.1.2 on 2022-11-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0007_alter_yearlybill_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='date_started',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='yearlybill',
            name='bill',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
